Detect cyclic dependencies in DRD
camunda-community-hub/dmn-scala pull request #148
Opened 2022-06-29 11:13 UTC by pihme

Opening this as draft PR for now. It does the job, but I feel there are a couple of points worth discussing first.

* in `DecisionTest` there is now this implicit class. Please let me know what you think of it, and in case you like it, whether we want to rewire the existing `parse(file)` calls to one of the new methods
* Not sure all the changes are idiomatic Scala. Any hints in that direction are very welcome
* In particular I am not happy about this construct:
```scala 
var foundCycle = false;

iterator.takeWhile(_ => !foundCycle).foreach(entry => foundCycle = doPartialCalculation(entry)

return foundCycle
```
* I made the assumption that it would be sufficient to detect the cycle, and it is not needed to return the elements of the cycle as part of the error message. Please let me know if you concur.
* The other question is whether we should also take care of loops in knowledge requirements, while we are at it.
* and anything else you stumble upon

2022-06-30 05:01 UTC, saig0 requested changes
@pihme looks good :+1: Thank you for fixing the bug :tada: 

I have a few minor suggestions with Scala tricks but only one major concern about the implicit test class. Please have a look at my comments.

2022-06-30 05:04 UTC, saig0 commented
> The other question is whether we should also take care of loops in knowledge requirements, while we are at it.

Yes, we should :+1: But we don't need to fix it in this PR. Feel free to tackle this part in a follow-up PR. Or, create an issue if you don't want to continue with it immediately.

2022-06-30 06:10 UTC, pihme commented
> r, create an issue if you don't want to continue with it immediately.

I will create a new issue. Since knowledge requirements cannot be modeled yet, I feel this fix can be deferred to a later date.
#149

2022-07-01 10:54 UTC, saig0 approved these changes
@pihme looks good :+1: Thank you :cake:

2022-07-01 10:54 UTC, merged